### ISSUE TITLE
upload-image api does not work as intended

### ISSUE THREAD

**Issue by mazchew** [mazchew/find-my-item#3]
![image](https://user-images.githubusercontent.com/61624815/175325951-023fc411-b029-41c1-87b0-0b7223fc4d7c.png)

**Comment by zhoyx** [comment]
Issue resolved, Vercel deployment Env variables autometically added interted commas to the environment variables. This was unknown to our team and thus the API paths where the request was posted was not as intended hence leading to the bug described above.
